name: velyntora
description: Editor de animacion 2D para escritorio, sencillo y extensible.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/velyntora_icon.png
  adaptive_icon_background: "#080A18"
  adaptive_icon_foreground: assets/branding/velyntora_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/branding/velyntora_icon.png
