package art.arcanokuro.velyntora.ui.drawing.components;

import android.app.Activity;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.Gravity;import android.view.View;import android.widget.*;
import art.arcanokuro.velyntora.ui.drawing.DrawingState;

public final class DrawingTopBar {
 private final Activity a;private final DrawingState state;private final int text=Color.rgb(235,235,235);private TextView sizeLabel,opacityLabel;
 public DrawingTopBar(Activity activity,DrawingState drawingState){a=activity;state=drawingState;}private int dp(int v){return Math.round(v*a.getResources().getDisplayMetrics().density);}
 public View createMenu(Runnable onBack,Runnable onUndo,Runnable onRedo,Runnable onExport,String documentName){LinearLayout bar=row();bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(8),0,dp(8),0);bar.setBackgroundColor(Color.rgb(43,43,43));Button back=flat("‹");back.setOnClickListener(v->onBack.run());bar.addView(back,new LinearLayout.LayoutParams(dp(42),dp(36)));Button undo=flat("↶");undo.setContentDescription("Deshacer");undo.setOnClickListener(v->onUndo.run());bar.addView(undo,new LinearLayout.LayoutParams(dp(42),dp(36)));Button redo=flat("↷");redo.setContentDescription("Rehacer");redo.setOnClickListener(v->onRedo.run());bar.addView(redo,new LinearLayout.LayoutParams(dp(42),dp(36)));Button export=flat("Exportar PNG");export.setOnClickListener(v->onExport.run());bar.addView(export,new LinearLayout.LayoutParams(-2,dp(36)));String[] menus={"Archivo","Editar","Ver","Imagen","Capa","Seleccionar","Filtros","Herramientas","Configuración","Ayuda"};for(String n:menus)bar.addView(flat(n),new LinearLayout.LayoutParams(-2,dp(36)));bar.addView(new Space(a),new LinearLayout.LayoutParams(0,1,1));TextView title=label("Velyntora — "+documentName,13);title.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);bar.addView(title,new LinearLayout.LayoutParams(dp(210),-1));return bar;}
 public View createToolOptions(){LinearLayout bar=row();bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(10),0,dp(10),0);bar.setBackgroundColor(Color.rgb(37,37,37));bar.addView(label("Herramienta",13));bar.addView(space(12));bar.addView(label("Tamaño",13));SeekBar size=new SeekBar(a);size.setMax(199);size.setProgress(state.brushSize()-1);sizeLabel=label(state.brushSize()+" px",13);size.setOnSeekBarChangeListener(listener(v->{state.setBrushSize(v+1);sizeLabel.setText(state.brushSize()+" px");}));bar.addView(size,new LinearLayout.LayoutParams(dp(150),-2));bar.addView(sizeLabel);bar.addView(space(16));opacityLabel=label("Opacidad "+state.opacity()+"%",13);SeekBar opacity=new SeekBar(a);opacity.setMax(100);opacity.setProgress(state.opacity());opacity.setOnSeekBarChangeListener(listener(v->{state.setOpacity(v);opacityLabel.setText("Opacidad "+state.opacity()+"%");}));bar.addView(opacityLabel);bar.addView(opacity,new LinearLayout.LayoutParams(dp(130),-2));return bar;}
 private SeekBar.OnSeekBarChangeListener listener(java.util.function.IntConsumer c){return new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean u){c.accept(p);}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}};}
 private Button flat(String v){Button b=new Button(a);b.setText(v);b.setTextColor(text);b.setTextSize(13);b.setAllCaps(false);b.setPadding(dp(7),0,dp(7),0);b.setMinWidth(0);b.setMinimumWidth(0);GradientDrawable g=new GradientDrawable();g.setColor(Color.TRANSPARENT);b.setBackground(g);return b;}private TextView label(String v,int s){TextView t=new TextView(a);t.setText(v);t.setTextColor(text);t.setTextSize(s);t.setGravity(Gravity.CENTER_VERTICAL);return t;}private Space space(int w){Space s=new Space(a);s.setLayoutParams(new LinearLayout.LayoutParams(dp(w),1));return s;}private LinearLayout row(){LinearLayout l=new LinearLayout(a);l.setOrientation(LinearLayout.HORIZONTAL);return l;}
}
